[package]
name = "web_push_subscription"
version = "0.1.0"
edition = "2021"

[lib]
name = "web_push_subscription"
path = "lib.rs"

[dependencies]
entities = { path = "../entities" }
common = { path = "../common", features = ["errors", "settings", "db"] }
db_adapters = { path = "../db_adapters" }

actix-web.workspace = true
sea-orm.workspace = true
serde.workspace = true
