[workspace]
resolver = "2"
members = [
    ".",
    "src/gohobi_ticket",
    "./migration",
    "src/entities",
    "src/common",
    "src/db_adapters",
    "src/user",
    "src/user_relation",
    "src/ticket",
    "src/server",
    "tests",
]
default-members = ["src/gohobi_ticket"]

[workspace.dependencies]
actix-session = { version = "0.10.1", features = ["redis-session"] }
actix-web = "4.10.2"
argon2 = { version = "0.5.3", default-features = false, features = [
    "password-hash",
    "rand",
    "std",
] }
async-std = { version = "1", features = ["attributes", "tokio1"] }
base64 = { version = "0.22.1", default-features = false }
chrono = "0.4.41"
deadpool-redis = "0.20.0"
dotenvy = "0.15.7"
env_logger = "0.11.8"
futures = { version = "0.3.31", default-features = false }
pbkdf2 = { version = "0.12.2", default-features = false, features = ["hmac"] }
sea-orm = { version = "~1.0", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "with-chrono",
    "with-json",
    "with-uuid",
] }
serde = "^1.0.219"
sha2 = { version = "0.10.9", default-features = false }
uuid = { version = "1.16.0", features = ["v7", "fast-rng"] }
