[package]
name = "tests"
version = "0.1.0"
edition = "2021"

[lib]
name = "tests"
path = "lib.rs"

[dependencies]
entities = { path = "../src/entities" }
general = { path = "../src/general", features = ["db", "redis", "settings"] }
user = { path = "../src/user" }
server = { path = "../src/server" }

actix-session.workspace = true
actix-web.workspace = true
chrono.workspace = true
sea-orm.workspace = true
uuid.workspace = true

[dev-dependencies]
actix-http = "3.10.0"
