[package]
name = "tests"
version = "0.1.0"
edition = "2021"

[lib]
name = "tests"
path = "lib.rs"

[dependencies]
entities = { path = "../src/entities" }
common = { path = "../src/common", features = ["db", "redis", "settings"] }
db_adapters = { path = "../src/db_adapters" }
user = { path = "../src/user" }
user_relation = { path = "../src/user_relation" }
ticket = { path = "../src/ticket" }
diary = { path = "../src/diary" }
diary_tag = { path = "../src/diary_tag" }
server = { path = "../src/server" }

actix-session.workspace = true
actix-web.workspace = true
chrono.workspace = true
sea-orm.workspace = true
uuid.workspace = true

[dev-dependencies]
actix-http = "3.10.0"
urlencoding = "2.1.3"
