[package]
name = "diary"
version = "0.1.0"
edition = "2021"

[lib]
name = "diary"
path = "lib.rs"

[dependencies]
entities = { path = "../entities" }
common = { path = "../common", features = [
    "errors",
    "settings",
    "db",
] }
domain_services = { path = "../domain_services" }

actix-web.workspace = true
chrono.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
