# Turn on debug to use these.

###
# @name login
POST {{endpoint}}/api/users/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
@user_relation_id=1

###
# @name list_diaries
GET {{endpoint}}/api/diaries/?user_relation_id={{user_relation_id}}


###
# @name create_diary
POST {{endpoint}}/api/diaries/
Content-Type: application/json

{
  "date": "2025-05-24",
  "entry": "test diary",
  "user_relation_id": {{user_relation_id}},
  "tag_ids": []
}

###
@diary_id=01970f8a-03e0-72e0-96d9-76a82ee3d60f

###
# @name mark_diary_read
PUT {{endpoint}}/api/diaries/{{diary_id}}/mark_read/
