# Turn on debug to use these.

###
# @name login
POST {{endpoint}}/api/users/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
# @name list_user_relations
GET {{endpoint}}/api/user_relations/

@user_relation_id=1

###
# @name list_giving_tickets
GET {{endpoint}}/api/tickets/?user_relation_id={{user_relation_id}}&is_giving

###
# @name list_receiving_tickets
GET {{endpoint}}/api/tickets/?user_relation_id={{user_relation_id}}&is_receiving

###
# @name create_ticket
POST {{endpoint}}/api/tickets/
Content-Type: application/json

{
  "ticket": {
    "gift_date": "2025-05-19",
    "description": "test ticket",
    "user_relation_id": {{user_relation_id}},
    "is_special": true,
    "is_draft": false,
    "status": "draft"
  }
}

###
@ticket_id=2303

###
# @name update_ticket
PUT {{endpoint}}/api/tickets/{{ticket_id}}/
Content-Type: application/json

{
  "ticket": {
    "description": "null",
    "status": "read"
  }
}

###
# @name read_ticket
PUT {{endpoint}}/api/tickets/{{ticket_id}}/read/
Content-Type: application/json

###
# @name make_wish
PUT {{endpoint}}/api/tickets/{{ticket_id}}/use/
Content-Type: application/json

{
  "ticket": {
    "use_description": "test"
  }
}

###
# @name delete_ticket
DELETE {{endpoint}}/api/tickets/{{ticket_id}}/
