# Turn on debug to use these.

###
# @name login
POST {{endpoint}}/api/users/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
# @name list_user_relations
GET {{endpoint}}/api/user_relations/

###
@user_relation_id=1

###
# @name special_ticket_availability
GET {{endpoint}}/api/user_relations/{{user_relation_id}}/special_ticket_availability/?year=2025&month=6

###
# @name available_tickets
GET {{endpoint}}/api/user_relations/{{user_relation_id}}/available_tickets/

###
# @name search
POST {{endpoint}}/api/user_relations/{{user_relation_id}}/search/
Content-Type: application/json

{
  "text": "Find me"
}

