//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "diaries_diary")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub entry: String,
    pub date: Date,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub user_relation_id: i64,
    pub user_1_status: String,
    pub user_2_status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::diaries_diarytagrelation::Entity")]
    DiariesDiarytagrelation,
    #[sea_orm(
        belongs_to = "super::user_relations_userrelation::Entity",
        from = "Column::UserRelationId",
        to = "super::user_relations_userrelation::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserRelationsUserrelation,
}

impl Related<super::diaries_diarytagrelation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiariesDiarytagrelation.def()
    }
}

impl Related<super::user_relations_userrelation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRelationsUserrelation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
