//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "diaries_diarytagrelation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub diary_id: Uuid,
    pub tag_master_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::diaries_diary::Entity",
        from = "Column::DiaryId",
        to = "super::diaries_diary::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DiariesDiary,
    #[sea_orm(
        belongs_to = "super::diaries_diarytag::Entity",
        from = "Column::TagMasterId",
        to = "super::diaries_diarytag::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DiariesDiarytag,
}

impl Related<super::diaries_diary::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiariesDiary.def()
    }
}

impl Related<super::diaries_diarytag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiariesDiarytag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
