//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::{entity::prelude::*, sqlx::types::chrono::Utc, ActiveValue::Set};
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "diaries_diarytagrelation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub diary_id: Uuid,
    pub tag_master_id: Uuid,
    #[sea_orm(belongs_to, from = "diary_id", to = "id", on_update = "NoAction", on_delete = "Cascade")]
    pub diary: HasOne<super::diaries_diary::Entity>,
    #[sea_orm(belongs_to, from = "tag_master_id", to = "id", on_update = "NoAction", on_delete = "Cascade")]
    pub tag: HasOne<super::diaries_diarytag::Entity>,
}

impl ActiveModelBehavior for ActiveModel {
    /// Create a new ActiveModel with default values. Also used by `Default::default()`.
    fn new() -> Self {
        Self {
            id: Set(Uuid::now_v7()),
            created_at: Set(Utc::now().into()),
            updated_at: Set(Utc::now().into()),
            ..ActiveModelTrait::default()
        }
    }
}
