//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "diaries_diary")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub entry: String,
    pub date: Date,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub user_relation_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(8))")]
    pub user_1_status: String,
    #[sea_orm(column_type = "String(StringLen::N(8))")]
    pub user_2_status: String,
    #[sea_orm(has_many)]
    pub diaries_diarytagrelations: HasMany<super::diaries_diarytagrelation::Entity>,
    #[sea_orm(belongs_to, from = "user_relation_id", to = "id", on_update = "NoAction", on_delete = "NoAction")]
    pub user_relations_userrelation: HasOne<super::user_relations_userrelation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
