//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub mod prelude;

pub mod custom_relations;
pub mod diaries_diary;
pub mod diaries_diarytag;
pub mod diaries_diarytagrelation;
pub mod tickets_ticket;
pub mod user_relations_userrelation;
pub mod users_user;
