//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::diaries_diary::Entity as DiariesDiary;
pub use super::diaries_diarytag::Entity as DiariesDiarytag;
pub use super::diaries_diarytagrelation::Entity as DiariesDiarytagrelation;
pub use super::tickets_ticket::Entity as TicketsTicket;
pub use super::user_relations_userrelation::Entity as UserRelationsUserrelation;
pub use super::users_user::Entity as UsersUser;
pub use super::web_push_subscription::Entity as WebPushSubscription;
pub use super::wish::Entity as Wish;
