//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use std::fmt::Display;

use sea_orm::{entity::prelude::*, sqlx::types::chrono::Utc, ActiveValue::Set};
use serde::{Deserialize, Serialize};

use crate::{user_relations_userrelation::UserRelationId, users_user::UserId};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tickets_ticket")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: TicketId,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub gift_date: Date,
    #[sea_orm(column_type = "String(StringLen::N(8))")]
    pub status: String,
    pub is_special: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub giving_user_id: UserId,
    pub user_relation_id: UserRelationId,
    #[sea_orm(belongs_to, from = "user_relation_id", to = "id", on_update = "NoAction", on_delete = "NoAction")]
    pub user_relations_userrelation: HasOne<super::user_relations_userrelation::Entity>,
    #[sea_orm(belongs_to, from = "giving_user_id", to = "id", on_update = "NoAction", on_delete = "NoAction")]
    pub users_user: HasOne<super::users_user::Entity>,
    #[sea_orm(has_one)]
    pub wish: HasOne<super::wish::Entity>,
}

#[derive(DeriveValueType, Clone, Debug, PartialEq, Eq, Serialize, Deserialize, Copy, Default)]
pub struct TicketId(i64);
impl Display for TicketId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}
impl From<i64> for TicketId {
    fn from(value: i64) -> Self {
        Self(value)
    }
}

impl ActiveModelBehavior for ActiveModel {
    /// Create a new ActiveModel with default values. Also used by `Default::default()`.
    fn new() -> Self {
        Self {
            created_at: Set(Utc::now().into()),
            updated_at: Set(Utc::now().into()),
            ..ActiveModelTrait::default()
        }
    }
}
