//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tickets_ticket")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub gift_date: Date,
    pub status: String,
    pub is_special: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub giving_user_id: i64,
    pub user_relation_id: i64,
    #[sea_orm(belongs_to, from = "user_relation_id", to = "id", on_update = "NoAction", on_delete = "NoAction")]
    pub user_relations_userrelation: HasOne<super::user_relations_userrelation::Entity>,
    #[sea_orm(belongs_to, from = "giving_user_id", to = "id", on_update = "NoAction", on_delete = "NoAction")]
    pub users_user: HasOne<super::users_user::Entity>,
    #[sea_orm(has_one)]
    pub wish: HasOne<super::wish::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
