//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use std::fmt::Display;

use sea_orm::{entity::prelude::*, sqlx::types::chrono::Utc, ActiveValue::Set};
use serde::{Deserialize, Serialize};

use crate::users_user::UserId;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_relations_userrelation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: UserRelationId,
    #[sea_orm(column_type = "String(StringLen::N(13))")]
    pub user_1_giving_ticket_img: Option<String>,
    #[sea_orm(column_type = "String(StringLen::N(13))")]
    pub user_2_giving_ticket_img: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub user_1_id: UserId,
    pub user_2_id: UserId,
    pub use_slack: bool,
    pub first_diary_date: Option<Date>,
    pub first_user_1_giving_ticket_date: Option<Date>,
    pub first_user_2_giving_ticket_date: Option<Date>,
    #[sea_orm(has_many)]
    pub diaries_diaries: HasMany<super::diaries_diary::Entity>,
    #[sea_orm(has_many)]
    pub diaries_diarytags: HasMany<super::diaries_diarytag::Entity>,
    #[sea_orm(has_many)]
    pub tickets_tickets: HasMany<super::tickets_ticket::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "UsersUser2",
        from = "user1_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users_user_2: HasOne<super::users_user::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "UsersUser1",
        from = "user2_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users_user_1: HasOne<super::users_user::Entity>,
    #[sea_orm(has_many)]
    pub wishes: HasMany<super::wish::Entity>,
}

#[derive(DeriveValueType, Clone, Debug, PartialEq, Eq, Serialize, Deserialize, Copy, Default)]
pub struct UserRelationId(i64);
impl Display for UserRelationId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}
impl From<i64> for UserRelationId {
    fn from(value: i64) -> Self {
        Self(value)
    }
}

impl ActiveModelBehavior for ActiveModel {
    /// Create a new ActiveModel with default values. Also used by `Default::default()`.
    fn new() -> Self {
        Self {
            created_at: Set(Utc::now().into()),
            updated_at: Set(Utc::now().into()),
            ..ActiveModelTrait::default()
        }
    }
}
