//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_relations_userrelation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_1_giving_ticket_img: Option<String>,
    pub user_2_giving_ticket_img: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub user_1_id: i64,
    pub user_2_id: i64,
    pub use_slack: bool,
    pub first_diary_date: Option<Date>,
    pub first_user_1_giving_ticket_date: Option<Date>,
    pub first_user_2_giving_ticket_date: Option<Date>,
    #[sea_orm(has_many)]
    pub diaries_diaries: HasMany<super::diaries_diary::Entity>,
    #[sea_orm(has_many)]
    pub diaries_diarytags: HasMany<super::diaries_diarytag::Entity>,
    #[sea_orm(has_many)]
    pub tickets_tickets: HasMany<super::tickets_ticket::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "UsersUser2",
        from = "user1_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users_user_2: HasOne<super::users_user::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "UsersUser1",
        from = "user2_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users_user_1: HasOne<super::users_user::Entity>,
    #[sea_orm(has_many)]
    pub wishes: HasMany<super::wish::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
