//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub password: String,
    pub last_login: Option<DateTimeWithTimeZone>,
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(has_many)]
    pub django_admin_logs: HasMany<super::django_admin_log::Entity>,
    #[sea_orm(has_many)]
    pub tickets_tickets: HasMany<super::tickets_ticket::Entity>,
    #[sea_orm(has_one)]
    pub web_push_subscription: HasOne<super::web_push_subscription::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
