//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user_relations_userrelation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_1_giving_ticket_img: Option<String>,
    pub user_2_giving_ticket_img: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub user_1_id: i64,
    pub user_2_id: i64,
    pub use_slack: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::diaries_diary::Entity")]
    DiariesDiary,
    #[sea_orm(has_many = "super::diaries_diarytag::Entity")]
    DiariesDiarytag,
    #[sea_orm(has_many = "super::tickets_ticket::Entity")]
    TicketsTicket,
    #[sea_orm(
        belongs_to = "super::users_user::Entity",
        from = "Column::User1Id",
        to = "super::users_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UsersUser2,
    #[sea_orm(
        belongs_to = "super::users_user::Entity",
        from = "Column::User2Id",
        to = "super::users_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UsersUser1,
    #[sea_orm(has_many = "super::wish::Entity")]
    Wish,
}

impl Related<super::diaries_diary::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiariesDiary.def()
    }
}

impl Related<super::diaries_diarytag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiariesDiarytag.def()
    }
}

impl Related<super::tickets_ticket::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TicketsTicket.def()
    }
}

impl Related<super::wish::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wish.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
