//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub password: String,
    pub last_login: Option<DateTimeWithTimeZone>,
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tickets_ticket::Entity")]
    TicketsTicket,
}

impl Related<super::tickets_ticket::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TicketsTicket.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
