//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "web_push_subscription")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub user_id: i64,
    pub device_name: String,
    pub endpoint: String,
    pub expiration_epoch_time: Option<i64>,
    pub p256dh_key: String,
    pub auth_key: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users_user::Entity",
        from = "Column::UserId",
        to = "super::users_user::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    UsersUser,
}

impl Related<super::users_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
