//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use std::{fmt::Display, str::FromStr};

use sea_orm::{entity::prelude::*, sea_query::ValueTypeErr, sqlx::types::chrono::Utc, ActiveValue::Set};
use serde::{Deserialize, Serialize};

use crate::{tickets_ticket::TicketId, user_relations_userrelation::UserRelationId};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "wish")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub status: WishStatus,
    #[sea_orm(unique)]
    pub ticket_id: TicketId,
    pub user_relation_id: UserRelationId,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(belongs_to, from = "ticket_id", to = "id", on_update = "NoAction", on_delete = "NoAction")]
    pub ticket: HasOne<super::tickets_ticket::Entity>,
    #[sea_orm(belongs_to, from = "user_relation_id", to = "id", on_update = "NoAction", on_delete = "NoAction")]
    pub user_relation: HasOne<super::user_relations_userrelation::Entity>,
    #[sea_orm(has_many)]
    pub replies: HasMany<super::wish_reply::Entity>,
}

#[derive(DeriveValueType, Clone, Debug, PartialEq, Eq, Serialize, Deserialize, Copy)]
#[sea_orm(value_type = "String", column_type = "String(StringLen::N(8))")]
pub enum WishStatus {
    Unread,
    Read,
}
impl FromStr for WishStatus {
    type Err = ValueTypeErr;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "unread" => Ok(WishStatus::Unread),
            "read" => Ok(WishStatus::Read),
            // NOTE: Invalid status should fall back to unread so that after reading, it will safely be turned to read.
            _ => Ok(WishStatus::Unread),
        }
    }
}
impl Display for WishStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::Unread => "unread",
                Self::Read => "read",
            }
        )
    }
}
impl Default for WishStatus {
    fn default() -> Self {
        Self::Unread
    }
}

impl ActiveModelBehavior for ActiveModel {
    /// Create a new ActiveModel with default values. Also used by `Default::default()`.
    fn new() -> Self {
        Self {
            id: Set(Uuid::now_v7()),
            created_at: Set(Utc::now().into()),
            updated_at: Set(Utc::now().into()),
            ..ActiveModelTrait::default()
        }
    }
}
