//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::{entity::prelude::*, sqlx::types::chrono::Utc, ActiveValue::Set};
use serde::{Deserialize, Serialize};

use crate::users_user::UserId;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "wish_replies")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(unique)]
    pub wish_id: Uuid,
    pub posted_by_id: UserId,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(belongs_to, from = "wish_id", to = "id", on_update = "NoAction", on_delete = "NoAction")]
    pub wish: HasOne<super::wish::Entity>,
    #[sea_orm(belongs_to, from = "posted_by_id", to = "id", on_update = "NoAction", on_delete = "NoAction")]
    pub posted_by: HasOne<super::users_user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {
    /// Create a new ActiveModel with default values. Also used by `Default::default()`.
    fn new() -> Self {
        Self { id: Set(Uuid::now_v7()), created_at: Set(Utc::now().into()), ..ActiveModelTrait::default() }
    }
}
