[package]
name = "gohobi_ticket"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gohobi_ticket"
path = "main.rs"

[[bin]]
name = "init_test_db"
path = "init_test_db.rs"

[dependencies]
common = { path = "../common", features = ["db", "redis", "settings"] }
entities = { path = "../entities" }
server = { path = "../server" }

actix-session.workspace = true
actix-web.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
