[package]
name = "user_relation"
version = "0.1.0"
edition = "2021"

[lib]
name = "user_relation"
path = "lib.rs"

[dependencies]
entities = { path = "../entities" }
common = { path = "../common", features = [
    "errors",
    "settings",
    "db",
    "factory",
] }
db_adapters = { path = "../db_adapters" }
ticket = { path = "../ticket" }
diary = { path = "../diary" }

actix-web.workspace = true
chrono.workspace = true
futures.workspace = true
sea-orm.workspace = true
serde.workspace = true
